/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedReposRouteImport } from './routes/_authenticated/repos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedReposRepoIdRouteImport } from './routes/_authenticated/repos_.$repoId'
import { Route as AuthenticatedPrPrIdRouteImport } from './routes/_authenticated/pr.$prId'
import { Route as ApiAiChatStreamRouteImport } from './routes/api/ai.chat.stream'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReposRoute = AuthenticatedReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReposRepoIdRoute =
  AuthenticatedReposRepoIdRouteImport.update({
    id: '/repos_/$repoId',
    path: '/repos/$repoId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPrPrIdRoute = AuthenticatedPrPrIdRouteImport.update({
  id: '/pr/$prId',
  path: '/pr/$prId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAiChatStreamRoute = ApiAiChatStreamRouteImport.update({
  id: '/api/ai/chat/stream',
  path: '/api/ai/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/repos': typeof AuthenticatedReposRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/pr/$prId': typeof AuthenticatedPrPrIdRoute
  '/repos/$repoId': typeof AuthenticatedReposRepoIdRoute
  '/api/ai/chat/stream': typeof ApiAiChatStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/repos': typeof AuthenticatedReposRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/pr/$prId': typeof AuthenticatedPrPrIdRoute
  '/repos/$repoId': typeof AuthenticatedReposRepoIdRoute
  '/api/ai/chat/stream': typeof ApiAiChatStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/demo': typeof DemoRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/repos': typeof AuthenticatedReposRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/pr/$prId': typeof AuthenticatedPrPrIdRoute
  '/_authenticated/repos_/$repoId': typeof AuthenticatedReposRepoIdRoute
  '/api/ai/chat/stream': typeof ApiAiChatStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/get-started'
    | '/login'
    | '/dashboard'
    | '/repos'
    | '/reviews'
    | '/settings'
    | '/pr/$prId'
    | '/repos/$repoId'
    | '/api/ai/chat/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/get-started'
    | '/login'
    | '/dashboard'
    | '/repos'
    | '/reviews'
    | '/settings'
    | '/pr/$prId'
    | '/repos/$repoId'
    | '/api/ai/chat/stream'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/demo'
    | '/get-started'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/repos'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/pr/$prId'
    | '/_authenticated/repos_/$repoId'
    | '/api/ai/chat/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DemoRoute: typeof DemoRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  ApiAiChatStreamRoute: typeof ApiAiChatStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repos': {
      id: '/_authenticated/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof AuthenticatedReposRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repos_/$repoId': {
      id: '/_authenticated/repos_/$repoId'
      path: '/repos/$repoId'
      fullPath: '/repos/$repoId'
      preLoaderRoute: typeof AuthenticatedReposRepoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pr/$prId': {
      id: '/_authenticated/pr/$prId'
      path: '/pr/$prId'
      fullPath: '/pr/$prId'
      preLoaderRoute: typeof AuthenticatedPrPrIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/ai/chat/stream': {
      id: '/api/ai/chat/stream'
      path: '/api/ai/chat/stream'
      fullPath: '/api/ai/chat/stream'
      preLoaderRoute: typeof ApiAiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReposRoute: typeof AuthenticatedReposRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPrPrIdRoute: typeof AuthenticatedPrPrIdRoute
  AuthenticatedReposRepoIdRoute: typeof AuthenticatedReposRepoIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReposRoute: AuthenticatedReposRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPrPrIdRoute: AuthenticatedPrPrIdRoute,
  AuthenticatedReposRepoIdRoute: AuthenticatedReposRepoIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DemoRoute: DemoRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  ApiAiChatStreamRoute: ApiAiChatStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
